In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import os
print(os.getcwd())

C:\Users\ADMIN


In [2]:
cars_train=pd.read_csv(r"C:\Users\ADMIN\Downloads\cars_train.csv",header=None)
cars_test=pd.read_csv(r"C:\Users\ADMIN\Downloads\cars_test.csv",header=None)

In [3]:
print(cars_train.shape)
cars_train.head()

(1382, 7)


0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [4]:
print(cars_test.shape)
cars_test.head()

(346, 7)


0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [5]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [7]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [8]:
#No feature selection are needed because all variables are relevant to problem statement 

In [9]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [10]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [11]:
#no outlier handling needed as we will be implementing tree based model annd also because all the variables are categorical not continuos...

In [12]:
cars_test.drop(["classes"],axis=1,inplace=True)
cars_test.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [13]:
colname=cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [15]:
cars_train.head(20)
#acc==>0
#good==>1
#unacc==>2
#vgood==>3+

buying  maint  doors  persons  lug_boot  safety  classes
0        3      0      1        2         2       1        2
1        1      3      1        1         2       2        2
2        1      0      3        2         0       1        2
3        0      2      2        0         2       2        2
4        1      1      1        2         0       2        1
5        1      1      0        1         0       0        3
6        1      0      3        2         0       0        3
7        0      2      3        1         2       1        2
8        2      1      1        0         2       1        2
9        3      1      1        1         0       1        2
10       2      3      3        2         1       1        2
11       1      0      3        2         1       2        0
12       2      3      1        1         0       1        2
13       3      3      0        1         0       2        2
14       3      2      3        0         0       2        2
15       2      2      2        2         0       0        3
16       0      2      1        2         2       1        2
17       0      0      0        2         2       1        2
18       1      2      0        1         2       0        1
19       1      1      2        0         1       0        2

In [16]:
colname=cars_test.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    cars_test[x]=le.fit_transform(cars_test[x])

In [18]:
cars_test.head(20)
#acc==>0
#good==>1
#unacc==>2
#vgood==>3+

buying  maint  doors  persons  lug_boot  safety
0        2      3      3        1         2       1
1        3      0      0        0         0       2
2        1      0      0        2         2       1
3        3      3      1        0         0       0
4        1      2      2        1         1       2
5        3      1      1        2         1       1
6        0      1      3        2         1       2
7        3      2      0        1         0       0
8        0      3      2        2         0       1
9        1      3      1        1         2       0
10       0      2      3        2         1       1
11       3      0      0        2         1       2
12       3      2      1        2         0       1
13       3      0      3        2         1       2
14       3      1      3        2         1       2
15       0      2      1        1         1       0
16       1      1      0        0         2       0
17       1      2      2        0         1       2
18       3      3      2        1         0       1
19       2      2      2        2         0       1

In [19]:
X=cars_train.values[:,0:-1]
Y=cars_train.values[:,-1]
Y=Y.astype(int)

In [20]:
print(X.shape)
print(Y.shape)

(1382, 6)
(1382,)


In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [22]:
print(X)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


In [23]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10,stratify=Y)#ensuring the class dist ratio is mantained

In [24]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1105, 6)
(1105,)
(277, 6)
(277,)


# Running Decision Tree Model

In [25]:
#predicting using the Decision_Tree_classifier
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10
                               ,criterion="gini")
#min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))


[(2, 2), (1, 1), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (3, 3), (0, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (3, 3), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2),

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 54   2   7   1]
 [  0  10   0   1]
 [  2   0 190   0]
 [  1   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.84      0.89        64
           1       0.83      0.91      0.87        11
           2       0.96      0.99      0.98       192
           3       0.82      0.90      0.86        10

    accuracy                           0.95       277
   macro avg       0.89      0.91      0.90       277
weighted avg       0.95      0.95      0.95       277

Accuracy of the model:  0.9494584837545126


In [27]:
model_DT.score(X_train,Y_train)

1.0

In [28]:
model_DT.feature_importances_

array([0.22575691, 0.1787049 , 0.04779911, 0.19114065, 0.1070919 ,
       0.24950654])

In [29]:
print(list(zip(cars_train.columns[0:-1],model_DT.feature_importances_)))

[('buying', 0.22575691221172356), ('maint', 0.17870490262570038), ('doors', 0.047799109234795606), ('persons', 0.19114064518600815), ('lug_boot', 0.10709189508483978), ('safety', 0.24950653565693254)]


In [30]:
sample=pd.DataFrame()
 
sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DT.feature_importances_
 
sample.sort_values("Imp value",ascending=False)


Column  Imp value
5    safety   0.249507
0    buying   0.225757
3   persons   0.191141
1     maint   0.178705
4  lug_boot   0.107092
2     doors   0.047799

In [31]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DT, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree
#A txt file will be created go to graphviz and paste that txt file and it will generate it...
#it will plot on training data.....

In [32]:
tree.export_graphviz?

Signature:
tree.export_graphviz(
    decision_tree,
    out_file=None,
    *,
    max_depth=None,
    feature_names=None,
    class_names=None,
    label='all',
    filled=False,
    leaves_parallel=False,
    impurity=True,
    node_ids=False,
    proportion=False,
    rotate=False,
    rounded=False,
    special_characters=False,
    precision=3,
    fontname='helvetica',
)
Docstring:
Export a decision tree in DOT format.

This function generates a GraphViz representation of the decision tree,
which is then written into `out_file`. Once exported, graphical renderings
can be generated using, for example::

    $ dot -Tps tree.dot -o tree.ps      (PostScript format)
    $ dot -Tpng tree.dot -o tree.png    (PNG format)

The sample counts that are shown are weighted with any sample_weights that
might be present.

Read more in the :ref:`User Guide <tree>`.

Parameters
----------
decision_tree : decision tree classifier
    The decision tree to be exported to GraphViz.

out_file : object o

In [33]:
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10
                               ,criterion="gini",
                               splitter="best",
                               min_samples_leaf=3,
                               min_samples_split=5,
                               max_depth=10,
                               max_leaf_nodes=100)
                               #max_max_features=0.6
#min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))


[(2, 2), (1, 1), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (3, 3), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (3, 3), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2),

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 59   2   3   0]
 [  1  10   0   0]
 [  5   0 187   0]
 [  1   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        64
           1       0.83      0.91      0.87        11
           2       0.98      0.97      0.98       192
           3       1.00      0.90      0.95        10

    accuracy                           0.96       277
   macro avg       0.93      0.93      0.93       277
weighted avg       0.96      0.96      0.96       277

Accuracy of the model:  0.9566787003610109


In [35]:
model_DT.score(X_train,Y_train)

0.9791855203619909

In [36]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DT, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree
#A txt file will be created go to graphviz and paste that txt file and it will generate it...
#it will plot on training data.....

In [37]:
#predicting using the Decision_Tree_classifier
from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
#min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
#fit the model on the data and predict the values
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))


[(2, 2), (1, 2), (1, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 0), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 0), (3, 3), (0, 2), (0, 0), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (3, 0), (3, 0), (0, 2), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (0, 2), (0, 0), (0, 2), (1, 2), (2, 2), (2, 2), (3, 0), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 0), (2, 2), (0, 2), (2, 2), (0, 3), (0, 3), (0, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (3, 2), (2, 0), (2, 0), (0, 2), (2, 2), (2, 2), (0, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2),

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 10   0  51   3]
 [  3   0   8   0]
 [ 20   0 172   0]
 [  5   0   3   2]]
Classification report: 
              precision    recall  f1-score   support

           0       0.26      0.16      0.20        64
           1       0.00      0.00      0.00        11
           2       0.74      0.90      0.81       192
           3       0.40      0.20      0.27        10

    accuracy                           0.66       277
   macro avg       0.35      0.31      0.32       277
weighted avg       0.58      0.66      0.61       277

Accuracy of the model:  0.6642599277978339


In [39]:
np.set_printoptions(suppress=True)
Y_pred_prob=classifier.predict_proba(X_test)
Y_pred_prob

array([[0.1455067 , 0.04323589, 0.81123141, 0.000026  ],
       [0.22347876, 0.03188998, 0.72945519, 0.01517608],
       [0.50488984, 0.05486076, 0.36320287, 0.07704653],
       ...,
       [0.35962384, 0.05058618, 0.58693592, 0.00285406],
       [0.05354699, 0.00873348, 0.93484206, 0.00287746],
       [0.10452281, 0.01510615, 0.87267525, 0.00769579]])

In [40]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
 
# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=1,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [41]:
# now, create a list with the objects 
models= [tree, knn, svm, logreg]


In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 54   2   7   1]
 [  0  10   0   1]
 [  2   0 190   0]
 [  1   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  94.94584837545126
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.84      0.89        64
           1       0.83      0.91      0.87        11
           2       0.96      0.99      0.98       192
           3       0.82      0.90      0.86        10

    accuracy                           0.95       277
   macro avg       0.89      0.91      0.90       277
weighted avg       0.95      0.95      0.95       277



[[ 56   0   8   0]
 [  6   5   0   0]
 [  4   0 188   0]
 [  4   0   2   4]]
The accuracy of the  KNeighborsClassifier  model is  91.33574007220217
Classification report:
               precision    recall  f1-score   support

           0       0.80      0.88      0.84        64
           1       1.00      0.45      0.62        11
           2       0.95      0.98      0.96       192


In [43]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [44]:
test=cars_test.values
test=scaler.transform(test)
#print(test)

In [45]:
# from sklearn.tree import DecisionTreeClassifier

# model_DT=DecisionTreeClassifier(random_state=10
#                                ,criterion="gini",
#                                splitter="best",
#                                min_samples_leaf=3,
#                                min_samples_split=5,
#                                max_depth=10,
#                                max_leaf_nodes=100)
#                                #max_max_features=0.6
# #min_samples_leaf,min_samples_split,max_depth,max_features,max_leaf_nodes
# #fit the model on the data and predict the values
# model_DT.fit(X_train,Y_train)
# Y_pred=model_DT.predict(X_test)
# # #print(Y_pred)
# # print(list(zip(Y_test,Y_pred)))


In [46]:
test_pred=model_DT.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 0, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2,
       0, 0, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 3, 0, 0, 2, 2, 0, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 3, 3, 0, 0,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [47]:
cars_test=pd.read_csv(r"C:\Users\ADMIN\Downloads\cars_test.csv",header=None)
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test["pred"]=test_pred
cars_test["pred"]=cars_test["pred"].replace({0:"acc",1:"good",2:"unacc",3:"vgood"})
cars_test.head()

buying  maint  doors persons lug_boot safety classes   pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report 
#confusion matrix
print(confusion_matrix(cars_test.classes,cars_test.pred))
print()
print("accuracy score")
print(accuracy_score(cars_test.classes,cars_test.pred))
print()
print("classification report:")
print(classification_report(cars_test.classes,cars_test.pred))

[[ 61   2   1   0]
 [  0  13   0   0]
 [  5   0 246   0]
 [  3   2   0  13]]

accuracy score
0.9624277456647399

classification report:
              precision    recall  f1-score   support

         acc       0.88      0.95      0.92        64
        good       0.76      1.00      0.87        13
       unacc       1.00      0.98      0.99       251
       vgood       1.00      0.72      0.84        18

    accuracy                           0.96       346
   macro avg       0.91      0.91      0.90       346
weighted avg       0.97      0.96      0.96       346



In [49]:
cars_test.to_excel("Decision Test Output.xlsx",header=True)

In [50]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=500,
                                          random_state=10, bootstrap=True,
                                         n_jobs=-1)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)
Y_pred

array([2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 0, 2, 2, 2, 3, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 3, 3, 0,
       2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2,
       3, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 3, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 3, 2,
       2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 3, 0, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 0, 3, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0,
       2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 1, 2, 3, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report 
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print()
print("accuracy score")
print(accuracy_score(Y_test,Y_pred))
print()
print("classification report:")
print(classification_report(Y_test,Y_pred))

[[ 59   2   3   0]
 [  2   9   0   0]
 [  1   0 191   0]
 [  1   0   0   9]]

accuracy score
0.9675090252707581

classification report:
              precision    recall  f1-score   support

           0       0.94      0.92      0.93        64
           1       0.82      0.82      0.82        11
           2       0.98      0.99      0.99       192
           3       1.00      0.90      0.95        10

    accuracy                           0.97       277
   macro avg       0.93      0.91      0.92       277
weighted avg       0.97      0.97      0.97       277



In [52]:
sample=pd.DataFrame()
sample["column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_RandomForest.feature_importances_
sample.sort_values("Imp value",ascending=False)

column  Imp value
5    safety   0.275472
3   persons   0.231335
0    buying   0.194578
1     maint   0.146605
4  lug_boot   0.081936
2     doors   0.070074

In [53]:
#predicting using the Extra_Trees_Classifier
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier(n_estimators=500,
                                          random_state=10, bootstrap=False)
 
#fit the model on the data and predict the values
model_EXT.fit(X_train,Y_train)
 
Y_pred=model_EXT.predict(X_test)
Y_pred

array([2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 0, 2, 2, 2, 3, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 3, 3, 0,
       2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2,
       3, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 3, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 3, 2,
       2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 3, 0, 2, 2, 2, 2, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 0, 3, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0,
       2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 3, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report 
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print()
print("accuracy score")
print(accuracy_score(Y_test,Y_pred))
print()
print("classification report:")
print(classification_report(Y_test,Y_pred))

[[ 60   0   4   0]
 [  2   9   0   0]
 [  2   0 190   0]
 [  1   0   0   9]]

accuracy score
0.9675090252707581

classification report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93        64
           1       1.00      0.82      0.90        11
           2       0.98      0.99      0.98       192
           3       1.00      0.90      0.95        10

    accuracy                           0.97       277
   macro avg       0.98      0.91      0.94       277
weighted avg       0.97      0.97      0.97       277



In [55]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier( random_state=10, bootstrap=True) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
    'n_estimators':[100,300,500,1000],       #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5)

In [56]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 300, 500, 1000]})

In [58]:
print('Best parameters found:\n',clf.best_params_)

Best parameters found:
 {'max_depth': 15, 'min_samples_leaf': 1, 'n_estimators': 300}


In [59]:
clf.best_score_ #accuracy of the best params using the 5-folf CV

0.9402714932126697

In [63]:
Y_pred=clf.predict(X_test)

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report 
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print()
print("accuracy score")
print(accuracy_score(Y_test,Y_pred))
print()
print("classification report:")
print(classification_report(Y_test,Y_pred))

[[ 58   0   6   0]
 [  3   8   0   0]
 [  1   0 191   0]
 [  2   0   0   8]]

accuracy score
0.9566787003610109

classification report:
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        64
           1       1.00      0.73      0.84        11
           2       0.97      0.99      0.98       192
           3       1.00      0.80      0.89        10

    accuracy                           0.96       277
   macro avg       0.97      0.86      0.90       277
weighted avg       0.96      0.96      0.96       277

